[package]
name = "byte"
version = "0.1.0"
edition = "2021"

[lib]
name = "byte"
path = "src/byte/lib.rs"

[[bin]]
name = "byte"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
