use super::*;

/// Basic token nodes generated by a default [`Scanner`].
#[derive(Debug, Eq, PartialEq)]
pub enum Token {
	Break,
	Indent(usize),
	Word(Name),
	Symbol(Name),
}

has_traits!(Token: IsNode);

impl IsNode for Token {
	fn precedence(&self, context: &Context) -> Option<(Precedence, Sequence)> {
		todo!()
	}

	fn evaluate(&self, context: &mut EvalContext) -> Result<NodeEval> {
		todo!()
	}
}
