use super::*;

/// Basic token nodes generated by a default [`Scanner`].
#[derive(Debug, Eq, PartialEq)]
pub enum Token {
	Indent(usize),
	Word(Name),
	Symbol(Name),
}

has_traits!(Token: IsNode);

impl IsNode for Token {}

/// Token generated for a line break.
#[derive(Debug, Eq, PartialEq)]
pub struct LineBreak;

has_traits!(LineBreak: IsNode);

impl IsNode for LineBreak {}
